# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Voz da Lei
email: contato@vozdalei.com.br
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vozdalei.com.br" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed
  - jekyll-assets

# FOLDER STRUCTURE
# ======================================================

source:       .
destination:  _site
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes

# JEKYLL-ASSETS 
# ======================================================

assets:
  sources:
    - assets/css
    - assets/img
    - assets/js
    - assets/svg

# SASS
# ======================================================

sass:
  style: compressed

# ROBOTS
# ======================================================

robots: index, follow

# COLLECTIONS
# ======================================================

collections:
  posts:
    output:    true  
  products:
    output:    true
    permalink: /produtos/:path

# EXCLUDED/KEPT FILES
# ======================================================

exclude: ['Gemfile', 'Gemfile.lock', 'LICENSE', 'README.md', '.idea/']
keep_files: ['.git', '.svn']
encoding: utf-8